Change check_deps to work with its original API

diff --git a/makepkg b/makepkg
--- a/makepkg
+++ b/makepkg
@@ -239,7 +239,14 @@ run_pacman() {
 check_deps() {
 	(( $# > 0 )) || return 0
 
-	dpkg-query -l "$@" >/dev/null
+	# A horrible hack to maintain check_deps' API
+	local f=$(mktemp)
+	local arglist=$(echo "$*" | sed 's/ +/\n/g' | sort >f)
+	local query=$(dpkg-query -Wf '${Package}\n' "$@" | sort)
+	local missing=$(echo "$query" | comm -23 f -)
+	rm f
+
+	printf "%s\n" "$missing"
 }
 
 handle_deps() {
@@ -262,6 +269,7 @@ handle_deps() {
 			error "$(gettext "'%s' failed to install missing dependencies.")" "$PACMAN"
 			exit 1 # TODO: error code
 		fi
+		sudo apt-mark auto $deplist
 	fi
 
 	# we might need the new system environment
@@ -281,15 +289,20 @@ resolve_deps() {
 	# deplist cannot be declared like this: local deplist=$(foo)
 	# Otherwise, the return value will depend on the assignment.
 	local deplist
-	deplist="$*"
-	(set +E; check_deps $*) && return $R_DEPS_SATISFIED
+	deplist="$(set +E; check_deps $*)" || exit 1
+	[[ -z $deplist ]] && return $R_DEPS_SATISFIED
 
 	if handle_deps $deplist; then
 		# check deps again to make sure they were resolved
-		(set +E; check_deps $*) && return $R_DEPS_SATISFIED
+		deplist="$(set +E; check_deps $*)" || exit 1
+		[[ -z $deplist ]] && return $R_DEPS_SATISFIED
 	fi
 
 	msg "$(gettext "Missing dependencies:")"
+	local dep
+	for dep in $deplist; do
+		msg2 "$dep"
+	done
 
 	return $R_DEPS_MISSING
 }
